// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: doctors.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const deleteDoctor = `-- name: DeleteDoctor :exec
DELETE FROM doctors
WHERE id = $1
`

func (q *Queries) DeleteDoctor(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteDoctor, id)
	return err
}

const getDoctorByEmail = `-- name: GetDoctorByEmail :one
SELECT id, name, email, phone, degree, specialization, password_hash, created_at, updated_at FROM doctors
WHERE email = $1
`

func (q *Queries) GetDoctorByEmail(ctx context.Context, email string) (Doctor, error) {
	row := q.db.QueryRowContext(ctx, getDoctorByEmail, email)
	var i Doctor
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Degree,
		&i.Specialization,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDoctorByID = `-- name: GetDoctorByID :one
SELECT id, name, email, phone, degree, specialization, password_hash, created_at, updated_at FROM doctors
WHERE id = $1
`

func (q *Queries) GetDoctorByID(ctx context.Context, id uuid.UUID) (Doctor, error) {
	row := q.db.QueryRowContext(ctx, getDoctorByID, id)
	var i Doctor
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Degree,
		&i.Specialization,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDoctors = `-- name: ListDoctors :many
SELECT id, name, email, phone, degree, specialization, password_hash, created_at, updated_at FROM doctors
ORDER BY created_at DESC
`

func (q *Queries) ListDoctors(ctx context.Context) ([]Doctor, error) {
	rows, err := q.db.QueryContext(ctx, listDoctors)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Doctor
	for rows.Next() {
		var i Doctor
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Phone,
			&i.Degree,
			&i.Specialization,
			&i.PasswordHash,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const registerDoctor = `-- name: RegisterDoctor :exec
INSERT INTO doctors( name, email, phone, degree, specialization, password_hash) 
VALUES ($1, $2, $3, $4, $5, $6)
`

type RegisterDoctorParams struct {
	Name           string
	Email          string
	Phone          string
	Degree         string
	Specialization string
	PasswordHash   string
}

func (q *Queries) RegisterDoctor(ctx context.Context, arg RegisterDoctorParams) error {
	_, err := q.db.ExecContext(ctx, registerDoctor,
		arg.Name,
		arg.Email,
		arg.Phone,
		arg.Degree,
		arg.Specialization,
		arg.PasswordHash,
	)
	return err
}

const updateDoctor = `-- name: UpdateDoctor :exec
UPDATE doctors
SET
  name = $1,
  email = $2,
  phone = $3,
  degree = $4,
  specialization = $5,
  updated_at = CURRENT_TIMESTAMP
WHERE id = $6
`

type UpdateDoctorParams struct {
	Name           string
	Email          string
	Phone          string
	Degree         string
	Specialization string
	ID             uuid.UUID
}

func (q *Queries) UpdateDoctor(ctx context.Context, arg UpdateDoctorParams) error {
	_, err := q.db.ExecContext(ctx, updateDoctor,
		arg.Name,
		arg.Email,
		arg.Phone,
		arg.Degree,
		arg.Specialization,
		arg.ID,
	)
	return err
}
