// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"

	"github.com/google/uuid"
)

type Doctor struct {
	ID             uuid.UUID
	Name           string
	Email          string
	Phone          string
	Degree         string
	Specialization string
	PasswordHash   string
	CreatedAt      sql.NullTime
	UpdatedAt      sql.NullTime
}

type Patient struct {
	ID             uuid.UUID
	Name           string
	Email          string
	Phone          string
	Address        string
	ReceptionistID uuid.UUID
	DoctorID       uuid.UUID
	PasswordHash   string
	CreatedAt      sql.NullTime
	UpdatedAt      sql.NullTime
}

type Receptionist struct {
	ID           uuid.UUID
	Name         string
	Email        string
	Phone        string
	Address      string
	PasswordHash string
	CreatedAt    sql.NullTime
	UpdatedAt    sql.NullTime
}
