// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: patient_history.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createPatientHistory = `-- name: CreatePatientHistory :exec
INSERT INTO patient_history (
    patient_id,
    doctor_id,
    symptoms,
    diagnosis,
    prescription,
    notes,
    tests_recommended,
    follow_up_date
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type CreatePatientHistoryParams struct {
	PatientID        uuid.UUID
	DoctorID         uuid.UUID
	Symptoms         string
	Diagnosis        string
	Prescription     string
	Notes            sql.NullString
	TestsRecommended string
	FollowUpDate     string
}

func (q *Queries) CreatePatientHistory(ctx context.Context, arg CreatePatientHistoryParams) error {
	_, err := q.db.ExecContext(ctx, createPatientHistory,
		arg.PatientID,
		arg.DoctorID,
		arg.Symptoms,
		arg.Diagnosis,
		arg.Prescription,
		arg.Notes,
		arg.TestsRecommended,
		arg.FollowUpDate,
	)
	return err
}

const deletePatientHistory = `-- name: DeletePatientHistory :exec
DELETE FROM patient_history
WHERE id = $1
`

func (q *Queries) DeletePatientHistory(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deletePatientHistory, id)
	return err
}

const getPatientHistoryByID = `-- name: GetPatientHistoryByID :one
SELECT id, patient_id, doctor_id, visit_date, symptoms, diagnosis, prescription, notes, tests_recommended, follow_up_date, created_at, updated_at FROM patient_history
WHERE id = $1
`

func (q *Queries) GetPatientHistoryByID(ctx context.Context, id uuid.UUID) (PatientHistory, error) {
	row := q.db.QueryRowContext(ctx, getPatientHistoryByID, id)
	var i PatientHistory
	err := row.Scan(
		&i.ID,
		&i.PatientID,
		&i.DoctorID,
		&i.VisitDate,
		&i.Symptoms,
		&i.Diagnosis,
		&i.Prescription,
		&i.Notes,
		&i.TestsRecommended,
		&i.FollowUpDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPatientHistoryByPatientID = `-- name: ListPatientHistoryByPatientID :many
SELECT id, patient_id, doctor_id, visit_date, symptoms, diagnosis, prescription, notes, tests_recommended, follow_up_date, created_at, updated_at FROM patient_history
WHERE patient_id = $1
ORDER BY visit_date DESC
`

func (q *Queries) ListPatientHistoryByPatientID(ctx context.Context, patientID uuid.UUID) ([]PatientHistory, error) {
	rows, err := q.db.QueryContext(ctx, listPatientHistoryByPatientID, patientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PatientHistory
	for rows.Next() {
		var i PatientHistory
		if err := rows.Scan(
			&i.ID,
			&i.PatientID,
			&i.DoctorID,
			&i.VisitDate,
			&i.Symptoms,
			&i.Diagnosis,
			&i.Prescription,
			&i.Notes,
			&i.TestsRecommended,
			&i.FollowUpDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePatientHistory = `-- name: UpdatePatientHistory :exec
UPDATE patient_history
SET
    symptoms = $1,
    diagnosis = $2,
    prescription = $3,
    notes = $4,
    tests_recommended = $5,
    follow_up_date = $6,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $7
`

type UpdatePatientHistoryParams struct {
	Symptoms         string
	Diagnosis        string
	Prescription     string
	Notes            sql.NullString
	TestsRecommended string
	FollowUpDate     string
	ID               uuid.UUID
}

func (q *Queries) UpdatePatientHistory(ctx context.Context, arg UpdatePatientHistoryParams) error {
	_, err := q.db.ExecContext(ctx, updatePatientHistory,
		arg.Symptoms,
		arg.Diagnosis,
		arg.Prescription,
		arg.Notes,
		arg.TestsRecommended,
		arg.FollowUpDate,
		arg.ID,
	)
	return err
}
