// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: patients.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const deletePatient = `-- name: DeletePatient :exec
DELETE FROM patients
WHERE id=$1
`

func (q *Queries) DeletePatient(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deletePatient, id)
	return err
}

const getPatientByEmail = `-- name: GetPatientByEmail :one
SELECT id, name, email, phone, address, receptionist_id, doctor_id, password_hash, created_at, updated_at FROM patients
WHERE email = $1
`

func (q *Queries) GetPatientByEmail(ctx context.Context, email string) (Patient, error) {
	row := q.db.QueryRowContext(ctx, getPatientByEmail, email)
	var i Patient
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Address,
		&i.ReceptionistID,
		&i.DoctorID,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPatientByID = `-- name: GetPatientByID :one

SELECT id, name, email, phone, address, receptionist_id, doctor_id, password_hash, created_at, updated_at FROM patients
WHERE id=$1
`

// patient's UUID
func (q *Queries) GetPatientByID(ctx context.Context, id uuid.UUID) (Patient, error) {
	row := q.db.QueryRowContext(ctx, getPatientByID, id)
	var i Patient
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Address,
		&i.ReceptionistID,
		&i.DoctorID,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPatients = `-- name: ListPatients :many
SELECT id, name, email, phone, address, receptionist_id, doctor_id, password_hash, created_at, updated_at FROM patients
ORDER BY created_at DESC
`

func (q *Queries) ListPatients(ctx context.Context) ([]Patient, error) {
	rows, err := q.db.QueryContext(ctx, listPatients)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Patient
	for rows.Next() {
		var i Patient
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Phone,
			&i.Address,
			&i.ReceptionistID,
			&i.DoctorID,
			&i.PasswordHash,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const registerPatient = `-- name: RegisterPatient :exec
INSERT INTO patients ( name, email, phone, address, receptionist_id, doctor_id, password_hash) 
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type RegisterPatientParams struct {
	Name           string
	Email          string
	Phone          string
	Address        string
	ReceptionistID uuid.UUID
	DoctorID       uuid.UUID
	PasswordHash   string
}

func (q *Queries) RegisterPatient(ctx context.Context, arg RegisterPatientParams) error {
	_, err := q.db.ExecContext(ctx, registerPatient,
		arg.Name,
		arg.Email,
		arg.Phone,
		arg.Address,
		arg.ReceptionistID,
		arg.DoctorID,
		arg.PasswordHash,
	)
	return err
}

const updatePatient = `-- name: UpdatePatient :exec
UPDATE patients
SET
    name=$1,
    email=$2,
    phone=$3,
    address=$4,
    doctor_id=$5,
    updated_at=CURRENT_TIMESTAMP
WHERE id=$6
`

type UpdatePatientParams struct {
	Name     string
	Email    string
	Phone    string
	Address  string
	DoctorID uuid.UUID
	ID       uuid.UUID
}

func (q *Queries) UpdatePatient(ctx context.Context, arg UpdatePatientParams) error {
	_, err := q.db.ExecContext(ctx, updatePatient,
		arg.Name,
		arg.Email,
		arg.Phone,
		arg.Address,
		arg.DoctorID,
		arg.ID,
	)
	return err
}
