// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: patients.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const deletePatient = `-- name: DeletePatient :exec
DELETE FROM patients
WHERE id=$1
`

func (q *Queries) DeletePatient(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deletePatient, id)
	return err
}

const getPatientByEmail = `-- name: GetPatientByEmail :one
SELECT id, name, email, phone, address, receptionist_id, doctor_id, password_hash, created_at, updated_at FROM patients
WHERE email = $1
`

func (q *Queries) GetPatientByEmail(ctx context.Context, email string) (Patient, error) {
	row := q.db.QueryRowContext(ctx, getPatientByEmail, email)
	var i Patient
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Address,
		&i.ReceptionistID,
		&i.DoctorID,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPatientDetailByID = `-- name: GetPatientDetailByID :one

SELECT id, name, email, phone, address, receptionist_id, doctor_id, password_hash, created_at, updated_at FROM patients
WHERE id=$1
`

// patient's UUID
func (q *Queries) GetPatientDetailByID(ctx context.Context, id uuid.UUID) (Patient, error) {
	row := q.db.QueryRowContext(ctx, getPatientDetailByID, id)
	var i Patient
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Address,
		&i.ReceptionistID,
		&i.DoctorID,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const registerPatient = `-- name: RegisterPatient :exec
INSERT INTO patients ( name, email, phone, address, receptionist_id, doctor_id, password_hash) 
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type RegisterPatientParams struct {
	Name           string
	Email          string
	Phone          string
	Address        string
	ReceptionistID uuid.UUID
	DoctorID       uuid.UUID
	PasswordHash   string
}

func (q *Queries) RegisterPatient(ctx context.Context, arg RegisterPatientParams) error {
	_, err := q.db.ExecContext(ctx, registerPatient,
		arg.Name,
		arg.Email,
		arg.Phone,
		arg.Address,
		arg.ReceptionistID,
		arg.DoctorID,
		arg.PasswordHash,
	)
	return err
}

const updatePatient = `-- name: UpdatePatient :exec
UPDATE patients
SET
    name=$1,
    email=$2,
    phone=$3,
    phone=$4,
    address=$5,
    updated_at=CURRENT_TIMESTAMP
WHERE id=$6
`

type UpdatePatientParams struct {
	Name    string
	Email   string
	Phone   string
	Phone_2 string
	Address string
	ID      uuid.UUID
}

func (q *Queries) UpdatePatient(ctx context.Context, arg UpdatePatientParams) error {
	_, err := q.db.ExecContext(ctx, updatePatient,
		arg.Name,
		arg.Email,
		arg.Phone,
		arg.Phone_2,
		arg.Address,
		arg.ID,
	)
	return err
}
