// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: receptionist.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const deleteReceptionist = `-- name: DeleteReceptionist :exec
DELETE FROM receptionist
WHERE id = $1
`

func (q *Queries) DeleteReceptionist(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteReceptionist, id)
	return err
}

const getReceptionistByEmail = `-- name: GetReceptionistByEmail :one
SELECT id, name, email, phone, address, password_hash, created_at, updated_at FROM receptionist
WHERE email = $1
`

func (q *Queries) GetReceptionistByEmail(ctx context.Context, email string) (Receptionist, error) {
	row := q.db.QueryRowContext(ctx, getReceptionistByEmail, email)
	var i Receptionist
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Address,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getReceptionistByID = `-- name: GetReceptionistByID :one
SELECT id, name, email, phone, address, password_hash, created_at, updated_at FROM receptionist
WHERE id = $1
`

func (q *Queries) GetReceptionistByID(ctx context.Context, id uuid.UUID) (Receptionist, error) {
	row := q.db.QueryRowContext(ctx, getReceptionistByID, id)
	var i Receptionist
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Address,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listReceptionists = `-- name: ListReceptionists :many
SELECT id, name, email, phone, address, password_hash, created_at, updated_at FROM receptionist
ORDER BY created_at DESC
`

func (q *Queries) ListReceptionists(ctx context.Context) ([]Receptionist, error) {
	rows, err := q.db.QueryContext(ctx, listReceptionists)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Receptionist
	for rows.Next() {
		var i Receptionist
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Phone,
			&i.Address,
			&i.PasswordHash,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const registerReceptionist = `-- name: RegisterReceptionist :exec
INSERT INTO receptionist ( name, email, phone, address, password_hash) 
VALUES ($1, $2, $3, $4, $5)
`

type RegisterReceptionistParams struct {
	Name         string
	Email        string
	Phone        string
	Address      string
	PasswordHash string
}

func (q *Queries) RegisterReceptionist(ctx context.Context, arg RegisterReceptionistParams) error {
	_, err := q.db.ExecContext(ctx, registerReceptionist,
		arg.Name,
		arg.Email,
		arg.Phone,
		arg.Address,
		arg.PasswordHash,
	)
	return err
}

const updateReceptionist = `-- name: UpdateReceptionist :exec
UPDATE receptionist
SET
  name = $1,
  email = $2,
  phone = $3,
  address = $4,
  updated_at = CURRENT_TIMESTAMP
WHERE id = $5
`

type UpdateReceptionistParams struct {
	Name    string
	Email   string
	Phone   string
	Address string
	ID      uuid.UUID
}

func (q *Queries) UpdateReceptionist(ctx context.Context, arg UpdateReceptionistParams) error {
	_, err := q.db.ExecContext(ctx, updateReceptionist,
		arg.Name,
		arg.Email,
		arg.Phone,
		arg.Address,
		arg.ID,
	)
	return err
}
